### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Hessel91** [publipresse/oc-forms-plugin#2]
Hi, do you have a fix? 

Update Failed
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'localhost.publipresse_forms_records' doesn't exist (SQL: select count(*) as aggregate from `publipresse_forms_records` where `unread` = 1)" on line 760 of C:\xamp\htdocs\localhost\vendor\laravel\framework\src\Illuminate\Database\Connection.php

**Comment by PubliAlex** [comment]
Strange, if you added the plugin via a project, did you used the

    php artisan project:sync

command to run migration ?

Or try to reinstall the module using : 

    php artisan plugin:refresh publipresse.forms

**Comment by PubliAlex** [comment]
Closed due to inactivity, feel free to reopen if needed.
