### ISSUE TITLE
Not sending auto-response 

### ISSUE THREAD

**Issue by jamesray2** [publipresse/oc-forms-plugin#3]
The form is not sending auto-notifications.

Tried {{ form.mailaddress }} and a normal mailaddress.

In both situations the auto reply does not work.

**Comment by PubliAlex** [comment]
> The form is not sending auto-notifications.
> 
> Tried {{ form.mailaddress }} and a normal mailaddress.
> 
> In both situations the auto reply does not work.

Could you attach your component configuration, to make some tests ?

Thank you

**Comment by jamesray2** [comment]
Hereby two screenshots.

When I add {{ form.emailadres }} to the subject, the mail address is displayed normal.
When I add {{ form.emailadres }} to Auto-response settings / Email field and I don't receive an auto-response.

![magiccomponent](https://github.com/publipresse/oc-forms-plugin/assets/7591805/4c9e5ef5-9234-438d-8f73-8e2a1ddb017b)

**Comment by PubliAlex** [comment]
The email field should just be the name of the form field. Try to simply put `emailadress` instead of `{{ form.emailadress }}` for the email field of autoresponse and let me know if it worked.

**Comment by jamesray2** [comment]
Ah, that worked.

Thanks!

**Comment by PubliAlex** [comment]
You are welcome
